### PR TITLE
Use a tokenizing filter

### LINKED ISSUE #92: Allow searching by disjoint substrings
For example, if I want to find NYT Crosswords from April 2020, my intuition is to type `NY Times April 2020` into the search bar. This doesn't work because downforacross is searching for that entire string in each title, and not finding it because it doesn't exist within a string like `NY Times, Monday, April 27, 2020`. But it's a very common technique to split each token in the search term, and return an result that contains `NY`, `Times`, `April`,  and `2020`. I believe this would be more powerful and intuitive.

### PR DESCRIPTION
**Pull request by TMiguelT**
Instead of the current (confusing) filter behaviour, we instead:

* Lower case the search string
* Split it into tokens

Then, each token must be present within the (lowercase) author name, or puzzle title or it is filtered out.

This is a draft PR until I can actually test it (see #116)

Closes #92.

### CODE REVIEW

File: src/components/PuzzleList/PuzzleList.js [hunk 1]
```diff
@@ -73,16 +73,18 @@ export default class PuzzleList extends PureComponent {
...
+    // Normalise case, and do it outside the filter loop for performance reasons
+    const author = entry.info.author.toLowerCase();
+    const title = entry.info.title.toLowerCase();
+    // Next, we normalise the search term, and then split it to allow for non-contiguous searches
+    const searchMatches = search
+      .toLowerCase()
+      .split(/\s/)
+      .every((token) => {
+        // Each token can be either in the author's name or in the puzzle's title
+        author.includes(token) || title.includes(token);
```
Comment (stevenhao) [inline src/components/PuzzleList/PuzzleList.js:85]: oops, missing `return`

**Comment by stevenhao** [comment]
Love this, fully support the idea! You should be able to test this without running a local backend, since the puzzle list is stored in firebase.

You can also test on the autodeploy links posted by vercel:  downforacrosscom-git-fork-tmiguelt-token-search.downforacross1.vercel.app.

**Comment by TMiguelT** [comment]
I tried that, but as in the other issue, I'm not able to actually upload puzzles to the site. And the puzzle list is empty, so I can't really test out this behaviour.

**Comment by TMiguelT** [comment]
And... now they're all visible. I have no idea what was going on there.

**Review by stevenhao — APPROVED** [review]
Looks great!

**Comment by stevenhao** [comment]
image
sweet, going to merge this. maybe a follow-up can be highlighting the parts of the puzzle that matches the search term.

**Comment by TMiguelT** [comment]
I suppose there's some argument for supporting search quotes, such that "LA Times" will only return that substring, and not "la" somewhere in the text and "times" somewhere in the text. But it depends on how you want the search to work: as a Google-esque plaintext search that implements features via search syntax, or as a kind of form with lots of fields that you can tweak.

This question also matters for the other thing search is missing: searching by date. Under the plaintext system you might type `date:2020-07-22`, whereas a form-based search might have a calendar popup for this purpose.

**Comment by stevenhao** [comment]
Yeah, I like the idea of coming up with a more powerful syntax -- something like [gmail's operators](https://support.google.com/mail/answer/7190?hl=en).

Another extension would be to hold the filter state (the Size / Status checkboxes) in the search bar itself, so checking & unchecking would just insert/delete search terms.

**Comment by TMiguelT** [comment]
That all seems quite doable. I wonder if there's a React or vanilla JS library that provides a framework for implementing an operator search like this. I can't find one, but admittedly it wouldn't be so hard to do manually.
